### ISSUE TITLE
Make the Controller a singelton 

### ISSUE THREAD

**Issue by MaayanWeizman** [DanBrima/ADSS_GROUP_A#37]

**Comment by aviad59** [comment]
פתרתי כי אני אלוף

**Comment by MaayanWeizman** [comment]
> זאת משימה של ספקים לגמרי ולא צריכה להיות מסומנת כgeneral, מלאי לא משתמשים בcontroller בכלל

היי זה לא נכון
אנחנו כתבנו את Store אבל הוא משותף לשתי המודלים...
הcontroller שולט גם על stores וגם על suppliers.

ובכל זאת תיקנת זאת 
יופי טופי

שיהיה בשמחות
