### ISSUE TITLE
merge the two tests

### ISSUE THREAD

**Issue by aviad59** [DanBrima/ADSS_GROUP_A#47]
inventory and suppliers are in different folder while suppliers are vanilla and inventory uses junit, both need to be in the same folder at least

**Comment by MaayanWeizman** [comment]
I'll try to create suppliers tests to be in the same format using junit.

**Comment by MaayanWeizman** [comment]
@aviad59 Where are inventory tests?

**Comment by aviad59** [comment]
out->tests->dev
